# Generated by Django 5.0.3 on 2024-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_author_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
