# Generated by Django 5.0.3 on 2024-03-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
