# Generated by Django 5.0.3 on 2024-04-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatushistory',
            name='user',
        ),
    ]
